apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-shortener
  namespace: pro
  labels:
    app: pro-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      containers:
        - name: pro-shortener-uwsgi
          image: registry.github.com/mazafard/shortener/shortener:VERSION
          args: ["uwsgi", "--module=shortenerr.wsgi:application", "--processes=4", "--protocol=http"]
          envFrom:
            - configMapRef:
                name: pro-shortener-config
        - name: pro-shortener-nginx
          image: registry.github.com/mazafard/shortener/shortener:VERSION
          args: ["nginx"]
          ports:
            - containerPort: 80
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pro-shortener-config
      imagePullSecrets:
        - name: reg
