# Generated by Django 3.0.5 on 2020-04-09 04:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()], verbose_name='link')),
                ('uri', models.CharField(blank=True, max_length=50, verbose_name='uri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='url', to=settings.AUTH_USER_MODEL, verbose_name='url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
