# Generated by Django 3.0.5 on 2020-04-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('browser', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateTimeField(verbose_name='visit date')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Session')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='url',
            field=models.ManyToManyField(related_name='sessions', through='service.SessionVisit', to='service.Url', verbose_name='url'),
        ),
    ]
